language: shell

services: 
  - docker


before_install: 
    - chmod +x cluster_configuration.sh

install:
    - "./cluster_configuration.sh"  
       
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
